"""db_criar_cadastro

Revision ID: 4ad7a1b96f74
Revises: 3c757246aba8
Create Date: 2023-08-16 13:27:33.906032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad7a1b96f74'
down_revision = '3c757246aba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastro_model', schema=None) as batch_op:
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastro_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.VARCHAR(length=14), nullable=False))

    # ### end Alembic commands ###
